# Generated by Django 3.2.5 on 2021-08-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='images')),
                ('menit', models.CharField(max_length=20)),
                ('kualitas', models.CharField(choices=[('hd', 'HD'), ('sd', 'SD'), ('webrip', 'WEBRIP')], default='hd', max_length=10)),
            ],
        ),
    ]
