# Generated by Django 3.2.5 on 2021-08-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='genre1',
            field=models.CharField(choices=[('Comedy', 'comedy'), ('Action', 'action'), ('Horror', 'horror'), ('Thriller', 'thriller')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='genre2',
            field=models.CharField(choices=[('Comedy', 'comedy'), ('Action', 'action'), ('Horror', 'horror'), ('Thriller', 'thriller')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='kualitas',
            field=models.CharField(choices=[('HD', 'hd'), ('SD', 'sd'), ('WEBRIP', 'webrip')], default='hd', max_length=10),
        ),
        migrations.AlterField(
            model_name='slider',
            name='poster',
            field=models.ImageField(upload_to='static'),
        ),
    ]
